### ISSUE TITLE
some insights on the recent GNOUSDT listing

### ISSUE THREAD

**Issue by d4fuQQ** [CyberPunkMetalHead/binance-trading-bot-new-coins#19]
hey man,
awesome stuff you're doing <3

about an hour ago GNO was listed on binance and the bot gave the following logs:
```
New coins detected: [{'symbol': 'GNOUSDT', 'price': '399.00000000'}, {'symbol': 'GNOBUSD', 'price': '408.00000000'}, {'symbol': 'GNOBNB', 'price': '0.61580000'}, {'symbol': 'GNOBTC', 'price': '0.00606900'}]
Preparing to buy GNOUSDT
3
APIError(code=-2010): Account has insufficient balance for requested action.
```

looking at the very 1st minute of the price, I suppose that means the bot noticed the coin rather late, i.e at a price of 399 although it was listed at 295 (I used the most recent config with "RUN_EVERY: 0.025"):
![image](https://user-images.githubusercontent.com/20617933/131300604-fa303dea-66fa-4682-beb5-2dc4fd1882c4.png)
Is that correct?

PS.: I "missed out" on purpose as I was just testing without any balance, so it's all fine with the APIError in line 4.

cheers

**Comment by Raynojam** [comment]
Here are my logs for comparison 

> New coins detected: [{'symbol': 'GNOUSDT', 'price': '390.00000000'}, {'symbol': 'GNOBUSD', 'price': '390.00000000'}, {'symbol': 'GNOBNB', 'price': '0.92700000'}, {'symbol': 'GNOBTC', 'price': '0.00606900'}]
> Preparing to buy GNOUSDT
> 3
> PLACING TEST ORDER
> Order created with 0.038 on GNOUSDT
> New coin detected, but GNOBUSD is currently in portfolio, or USDT does not match
> New coin detected, but GNOBNB is currently in portfolio, or USDT does not match
> New coin detected, but GNOBTC is currently in portfolio, or USDT does not match
> sold GNOUSDT at -3.6666666666666696

**Comment by d4fuQQ** [comment]
interesting that my USDT & BUSD are different while yours are not..

perhaps the logs should also explcitily include at what price an order was bought and sold. then it would also be more clear what the percentage in the last line is based on for a particular coin/order :)

**Comment by goblej216** [comment]
Here are my logs running a test last night. Looks like I was late on the jump as well plus I had a weird network issue not sure what that was about.

> working...
HTTPSConnectionPool(host='api.binance.com', port=443): Read timed out. (read timeout=10)
('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
New coins detected: [{'symbol': 'GNOUSDT', 'price': '328.20000000'}, {'symbol': 'GNOBUSD', 'price': '328.50000000'}, {'symbol': 'GNOBNB', 'price': '0.68800000'}, {'symbol': 'GNOBTC', 'price': '0.00685400'}]
Preparing to buy GNOUSDT
3
PLACING TEST ORDER
Order created with 0.046 on GNOUSDT
New coin detected, but GNOBUSD is currently in portfolio, or USDT does not match
New coin detected, but GNOBNB is currently in portfolio, or USDT does not match
New coin detected, but GNOBTC is currently in portfolio, or USDT does not match
('Connection aborted.', OSError(50, 'Network is down'))
^CTraceback (most recent call last):
  File "/Users/joe/binancebot/./main.py", line 197, in <module>
    main()
  File "/Users/joe/binancebot/./main.py", line 140, in main
    new_coins, all_coins_recheck = get_new_coins(all_coins)
  File "/Users/joe/binancebot/./main.py", line 28, in get_new_coins
    return [new_coins for new_coins in all_coins_recheck if new_coins['symbol'] not in [coin['symbol'] for coin in all_coins]], all_coins_recheck
  File "/Users/joe/binancebot/./main.py", line 28, in <listcomp>
    return [new_coins for new_coins in all_coins_recheck if new_coins['symbol'] not in [coin['symbol'] for coin in all_coins]], all_coins_recheck
  File "/Users/joe/binancebot/./main.py", line 28, in <listcomp>
    return [new_coins for new_coins in all_coins_recheck if new_coins['symbol'] not in [coin['symbol'] for coin in all_coins]], all_coins_recheck
KeyboardInterrupt
joe@Joes-MacBook-Pro-2:~/binancebot|main⚡ ⇒  python3 ./main.py
working...
sold GNOUSDT at -3.900060938452167

My config:

> RUN_EVERY: 0.1

My order.json is empty and here is my sold.json:

`    "GNOUSDT": {
        "symbol": "GNOUSDT",
        "price": "315.40000000",
        "volume": 0.046,
        "time": 1630326322.613947,
        "profit": -12.800000000000011,
        "relative_profit": -3.9
    }`
