### ISSUE TITLE
running getting this issus on rpi4 

### ISSUE THREAD

**Issue by Scout-lander** [CyberPunkMetalHead/binance-trading-bot-new-coins#25]
python3 main.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new                                                                                                                                                             _conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in                                                                                                                                                              create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in                                                                                                                                                              urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in                                                                                                                                                              _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in                                                                                                                                                              _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in conn                                                                                                                                                             ect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new                                                                                                                                                             _conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnecti                                                                                                                                                             on object at 0xb555db10>: Failed to establish a new connection: [Errno -2] Name                                                                                                                                                              or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in                                                                                                                                                              urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in incr                                                                                                                                                             ement
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.binance_                                                                                                                                                             tld', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewConne                                                                                                                                                             ctionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb555db10>: F                                                                                                                                                             ailed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from trade_client import *
  File "/home/pi/bot/trade_client.py", line 3, in <module>
    client = load_binance_creds('auth/auth.yml')
  File "/home/pi/bot/auth/binance_auth.py", line 11, in load_binance_creds
    return Client(api_key = auth['binance_api'], api_secret = auth['binance_secr                                                                                                                                                             et'], tld = "com" if 'binance_tld' not in auth else auth['binance_tld'])
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 300                                                                                                                                                             , in __init__
    self.ping()
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 526                                                                                                                                                             , in ping
    return self._get('ping', version=self.PRIVATE_API_VERSION)
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 371                                                                                                                                                             , in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 334                                                                                                                                                             , in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 314                                                                                                                                                             , in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in reque                                                                                                                                                             st
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.binance.binan                                                                                                                                                             ce_tld', port=443): Max retries exceeded with url: /api/v3/ping (Caused by NewCo                                                                                                                                                             nnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb555db10>                                                                                                                                                             : Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by nevsnevs** [comment]
Have you set the new field binance_tld in the config.yml?

Looks like the script wants to connect to host='api.binance.binance tld' which is non-existent.

I think op merged the code with this new field, but didnt update the Instructions.

**Comment by dannylknight33** [comment]
This is Maria Knight…. Danny knight is the client that is trying to have you to take my bitcoin for payment I presume….. This is a serious deal as I have a second restraining order for him after he’s been charged with aggravated assault, child endangerment in the 1st degree, and aggravated stalking…. You have been allowing him to have access to all my cameras, Alexas, and alarm system that I need to protect myself from him. This was back in October  2020 and he is a huge threat to our safety. He is acting as me through an old device and this is his actual info. ***@***.*** and 470-733-9541. Please remove all bots asap and I can send you legal documents if needed as this is extremely illegal what your doing… 

I may have to contact you each individually as he is now faced with felony charges once this is reported.  I have your info don’t worry and all the data I needed on a separate device locked so I’m good. Please be careful doing this it can hurt people. But you all did a great job as I have watched this for the past for days. Any info sold or taken please delete or I will take yours… Thanks!!! 


Please contact me at 770-608-6773 (you already have it though lol ) if you need me.

**Comment by dannylknight33** [comment]
hey I am the person you are trying to hack... Danny Knight has charges for aggravated assault, stalking, and intent to harm a child in the 1st the degree and is pretending to be me and has been given access to everything that I use to protect myself. I have a restraining order out since October of last year and no access to my my cameras and he listens through my Bluetooth devices now. He strangled me last time and got off with 12 months probation with it covid so now he could kill me freely and knows when I don't have my alarm on or cameras or anything for that matter as. well as my son and that's on you guys... so stop with the. bitcoin you can get in cause I can code to. I am not reporting anyone either cause you guys are really good at this but please do some digging first or you're worse than he his. Spread Love and Light ;)  and m are people pay you up front for services you aren't gangster level yet. lol good luck to you

**Comment by Scout-lander** [comment]
ohh shoot snap yeah, whts the tld

**Comment by nevsnevs** [comment]
Top-Level Domain com or us

**Comment by dannylknight33** [comment]
thank you for being so understanding and nice about this... what all do you need?

**Comment by Scout-lander** [comment]
yeah thanks so much i ended up working out the tld  , well i think
ran it again poped up with Working left it for a couple hours then desided to close it and got this 

 python main.py
working...
^CTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 219, in <module>
    main()
  File "main.py", line 163, in main
    new_coins = get_new_coins(coin_seen_dict)
  File "main.py", line 42, in get_new_coins
    all_coins_recheck = get_all_coins()
  File "main.py", line 21, in get_all_coins
    return client.get_all_tickers()
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 571, in get_all_tickers
    return self._get('ticker/price', version=self.PRIVATE_API_VERSION)
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 371, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/binance/client.py", line 314, in _request
    self.response = getattr(self.session, method)(uri, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

**Comment by senic35** [comment]
@Scout-lander Did you read the error message at all? Look at the last line, it says KeyboardInterrupt.
All that means is that you stopped the program mid-execution.

**Comment by mevljas** [comment]
I've opened a pull request fixing this. #15

**Comment by Mikegarylee01** [comment]
> ohh shoot snap yeah, whts the tld

:ɪ •ᴡɪʟʟ •ɪɴᴛʀᴏᴅᴜᴄᴇ •ʏᴏᴜ •on• how •to •make• higher  profit•through•ɪɴᴠᴇꜱᴛᴍᴇɴᴛ No lose Text' me' on' •ᴡʜᴀᴛꜱᴀᴘᴘ••
+13234525476.

**Comment by Mikegarylee01** [comment]
> Top-Level Domain com or us

:ɪ •ᴡɪʟʟ •ɪɴᴛʀᴏᴅᴜᴄᴇ •ʏᴏᴜ •on• how •to •make• higher  profit•through•ɪɴᴠᴇꜱᴛᴍᴇɴᴛ No lose Text' me' on' •ᴡʜᴀᴛꜱᴀᴘᴘ••
+13234525476.

**Comment by Mikegarylee01** [comment]
> thank you for being so understanding and nice about this... what all do you need?
> 

:ɪ •ᴡɪʟʟ •ɪɴᴛʀᴏᴅᴜᴄᴇ •ʏᴏᴜ •on• how •to •make• higher  profit•through•ɪɴᴠᴇꜱᴛᴍᴇɴᴛ No lose Text' me' on' •ᴡʜᴀᴛꜱᴀᴘᴘ••
+13234525476.
