### ISSUE TITLE
GALAUSDT listing 13/09 feedback

### ISSUE THREAD

**Issue by bragg2012** [CyberPunkMetalHead/binance-trading-bot-new-coins#40]
Anyone have any joy with this using the latest margin script?  Looks like mine traded at a loss of -6.146

@CyberPunkMetalHead can you confirm which wallet the USDT needs to be in on our binance accounts, is it ok in the spot wallet or should we move to a specific margin wallet to execute the trades now?

**Comment by Lautaro-L** [comment]
I made some small modification to the original script, and today I'm going to try save some time in some parts. But as today it was able to make a profit, it managed to buy it quickly but the tsl didn't kick in I have to check what parameters I was using but i sold it manually

**Comment by easyguyme** [comment]
@Lautaro-L Do you mind  sharing your script?

**Comment by Lautaro-L** [comment]
Yes of course, let me finish some changes, I'll make a fork and remove some credentials then is good to go. Also I added telegram support to send messages there since I run it on a headless server and I'm not seeing console often.
it isn't tested this time so I recommend plugin it on the testnet

**Comment by Hammer632** [comment]
> Yes of course, let me finish some changes, I'll make a fork and remove some credentials then is good to go. Also I added telegram support to send messages there since I run it on a headless server and I'm not seeing console often.
> it isn't tested this time so I recommend plugin it on the testnet

Thank you

**Comment by Hammer632** [comment]
> Yes of course, let me finish some changes, I'll make a fork and remove some credentials then is good to go. Also I added telegram support to send messages there since I run it on a headless server and I'm not seeing console often.
> it isn't tested this time so I recommend plugin it on the testnet

Heeeee testing your script and run into an error information for others the file TRADE_CLIENT.PY has line from your local computer in it : client = load_binance_creds(r'C:\Users\MINERO\Documents\binance-trading-bot-new-coins\auth\auth.yml')
And we dont have access to your computer so it cant find it lol

**Comment by Lautaro-L** [comment]
Lol i forgot to delete that part I'm on it

**Comment by Hammer632** [comment]
> Lol i forgot to delete that part I'm on it
> Edit: done

Heee Lautaro question from my side, when i run your script i get this error ModuleNotFoundError: No module named 'auth.binance_auth'
When i run the other script with the same line in it it runs just fine. Do you have an idea?

**Comment by Lautaro-L** [comment]
Hmm really weird, since i didn't touch the import lines and the script runs with no trouble for me, really weird any more info about the error code?

**Comment by Hammer632** [comment]
> Hmm really weird, since i didn't touch the import lines and the script runs with no trouble for me, really weird any more info about the error code?

This is the complete error
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from trade_client import *
  File "/home/pi/Desktop/botwithtelegram/trade_client.py", line 1, in <module>
    from auth.binance_auth import *
ModuleNotFoundError: No module named 'auth.binance_auth'

**Comment by Lautaro-L** [comment]
Tested it a couple times on different computers and I couldn't replicate the issue

**Comment by CyberPunkMetalHead** [comment]
Guys, the margin script hasn't yet been pushed. Will push soon but please be aware that currently it's still placing spot buy orders. I realised that there are some complexities that need to be addressed such as: not all coins are being listed on margin/futures trading which effectively means that shorting coins can only work if said coin is pre-owned.

I've also enabled discussions for this repo so we can talk about this in more detail.

**Comment by Lautaro-L** [comment]
Yes I saw the videos shorting is a good strategy, I thought on porting the code to c++ or c if the changes I made don't manages to place the spot order fast enough currently is really fast, but another problem that might occur is lack of liquidity to fullfil spot orders since those are filled chronologically, but limit orders with a value a little higher than market price fills faster.
And about the margin one I think you can place both long and shorts orders one first if you catch the coin quick enough but we can talk on the channel not here

**Comment by CelliHere** [comment]
for some reason my bot didn't buy GALA. I think it was still stuck in ELF, trying to track order/sell. Is that normal?
