### ISSUE TITLE
facing issues not working please check it there might be some issues with the import module 

### ISSUE THREAD

**Issue by CadburySwaps** [CyberPunkMetalHead/binance-trading-bot-new-coins#65]
amanjyosMacBook:binance-trading-bot-new-coins amanjyotsingh$ python main.py 
  File "main.py", line 157
    print(f'updated tp: {round(new_tp, 3)} and sl: {round(new_sl, 3)}')
                                                                     ^
SyntaxError: invalid syntax
amanjyosMacBook:binance-trading-bot-new-coins amanjyotsingh$ python3 main.py 
Traceback (most recent call last):
  File "/Users/amanjyotsingh/binance_api/binance-trading-bot-new-coins/main.py", line 4, in <module>
    from new_listings_scraper import *
  File "/Users/amanjyotsingh/binance_api/binance-trading-bot-new-coins/new_listings_scraper.py", line 5, in <module>
    from chromedriver_py import binary_path
ModuleNotFoundError: No module named 'chromedriver_py'

**Comment by CadburySwaps** [comment]
> amanjyosMacBook:binance-trading-bot-new-coins amanjyotsingh$ python main.py File "main.py", line 157 print(f'updated tp: {round(new_tp, 3)} and sl: {round(new_sl, 3)}') ^ SyntaxError: invalid syntax amanjyosMacBook:binance-trading-bot-new-coins amanjyotsingh$ python3 main.py Traceback (most recent call last): File "/Users/amanjyotsingh/binance_api/binance-trading-bot-new-coins/main.py", line 4, in from new_listings_scraper import * File "/Users/amanjyotsingh/binance_api/binance-trading-bot-new-coins/new_listings_scraper.py", line 5, in from chromedriver_py import binary_path ModuleNotFoundError: No module named 'chromedriver_py'




amanjyosMacBook:binance-trading-bot-new-coins amanjyotsingh$ pip3 install selenium
Requirement already satisfied: selenium in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from selenium) (1.26.7)
amanjyosMacBook:binance-trading-bot-new-coins amanjyotsingh$ pip3 install chromedriver_py
Collecting chromedriver_py
  Downloading chromedriver_py-95.0.4638.17-py3-none-any.whl (24.2 MB)
     |████████████████████████████████| 24.2 MB 223 kB/s 
Installing collected packages: chromedriver-py
Successfully installed chromedriver-py-95.0.4638.17
amanjyosMacBook:binance-trading-bot-new-coins amanjyotsingh$ 

that's going to work

**Comment by CadburySwaps** [comment]
![Screen Shot 2021-10-02 at 7 52 11 PM](https://user-images.githubusercontent.com/89444214/135721532-fc133e4c-0c42-4eb9-b0d7-ba99a50dd842.png)
i got this

**Comment by CadburySwaps** [comment]
what should i do next
please help!!!

**Comment by calvin200001** [comment]
> what should i do next please help!!!

https://www.google.com/chrome/beta/ download for mac. then change the name from "Google Chrome beta" to  "Google Chrome".
Then in finder do "Command shift g".
Then paste this path in there: /Applications/Google Chrome.app/Contents/macos
Then change the name of that as well from "Google Chrome beta" to  "Google Chrome"
That seemed to work for me.

**Comment by webdesign7** [comment]
`pip install chromedriver-py`

**Comment by CryptoAngel** [comment]
Hi,
Have you managed to solve this?
File "main.py", line 157
print(f'updated tp: {round(new_tp, 3)} and sl: {round(new_sl, 3)}')
SyntaxError: invalid syntax

I face the same but no one reply ;-(
