### ISSUE TITLE
Error: File "main.py", line 157

### ISSUE THREAD

**Issue by CryptoAngel** [CyberPunkMetalHead/binance-trading-bot-new-coins#87]
Hello,

Trying to run the code result with error:

File "main.py", line 157
     print(f'updated tp: {round(new_tp, 3)} and sl: {round(new_sl, 3)}')
SyntaxError: invalid syntax

Can help resolve?

Regards

**Comment by acediatic** [comment]
What version of Python are you running? The above line runs fine on mine. I suspect it's due to the fact that format strings were introduced in `python 3.7`. See [here](https://realpython.com/python-f-strings/) for more info on f strings.

So make sure your version of Python is `>=3.7`. You can check your python version by running `python --version` in a terminal.

**Comment by CryptoAngel** [comment]
Thank you, resolved it, needed to run it with the command python3 main.py

**Comment by CryptoAngel** [comment]
Now I have new issue, what are those?

working...
Exception in thread Thread-2 (search_and_update):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ea/Library/Mobile Documents/com~apple~CloudDocs/Programing/binance-trading-bot-new-coins-main/new_listings_scraper.py", line 69, in search_and_update
    latest_coin = get_last_coin()
  File "/Users/ea/Library/Mobile Documents/com~apple~CloudDocs/Programing/binance-trading-bot-new-coins-main/new_listings_scraper.py", line 33, in get_last_coin
    uppers = ''.join(item[1] for item in enum if item[1].isupper() and (enum[enum.index(item)+1][1].isupper() or enum[enum.index(item)+1][1]==' ' or enum[enum.index(item)+1][1]==')') )
  File "/Users/ea/Library/Mobile Documents/com~apple~CloudDocs/Programing/binance-trading-bot-new-coins-main/new_listings_scraper.py", line 33, in <genexpr>
    uppers = ''.join(item[1] for item in enum if item[1].isupper() and (enum[enum.index(item)+1][1].isupper() or enum[enum.index(item)+1][1]==' ' or enum[enum.index(item)+1][1]==')') )
IndexError: list index out of range

**Comment by CryptoAngel** [comment]
also get this 
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
