### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by awildfig** [CyberPunkMetalHead/binance-trading-bot-new-coins#9]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from trade_client import *
  File "/home/nathan/binance/trade_client.py", line 4
    """Converts the volume given in QUANTITY from USDT to the each coin's volume"""
    ^
IndentationError: expected an indented block

issue when running main.py

**Comment by altchater** [comment]
Looks like the function was over-indented.  Here is a little fix #10.
