### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by trumpest2** [CyberPunkMetalHead/binance-trading-bot-new-coins#97]
DevTools listening on ws://127.0.0.1:50614/devtools/browser/af9fb21d-0475-468f-9a21-938899a9bacd
Traceback (most recent call last):
  File "C:\bot\main.py", line 4, in <module>
    from new_listings_scraper import *
  File "C:\bot\new_listings_scraper.py", line 15, in <module>
    driver = webdriver.Chrome(executable_path=binary_path, options=chrome_options)
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 99.0.4844.82 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00F58BD3+2395091]
        Ordinal0 [0x00EEACA1+1944737]
        Ordinal0 [0x00DDD008+839688]
        Ordinal0 [0x00DFD1A3+971171]
        Ordinal0 [0x00DF8DAA+953770]
        Ordinal0 [0x00DF6661+943713]
        Ordinal0 [0x00E296F0+1152752]
        Ordinal0 [0x00E2934A+1151818]
        Ordinal0 [0x00E249D6+1133014]
        Ordinal0 [0x00DFEF76+978806]
        Ordinal0 [0x00DFFE86+982662]
        GetHandleVerifier [0x0110C912+1719138]
        GetHandleVerifier [0x011BB2CD+2434333]
        GetHandleVerifier [0x00FF4001+569937]
        GetHandleVerifier [0x00FF3066+565942]
        Ordinal0 [0x00EF265B+1975899]
        Ordinal0 [0x00EF72A8+1995432]
        Ordinal0 [0x00EF7395+1995669]
        Ordinal0 [0x00F002F1+2032369]
        BaseThreadInitThunk [0x75C3FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77807A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77807A4E+238]

**Comment by trumpest2** [comment]
i download a lower version of chromedriver to match the cheom and fix it up.
