### ISSUE TITLE
ModuleNotFoundError: No module named 'auth.binance_auth'

### ISSUE THREAD

**Issue by Siliphon** [CyberPunkMetalHead/binance-trading-bot-new-coins#99]
C:\Users\Silph\AppData\Local\Programs\Python\Python310\lib\site-packages\auth\__init__.py:3: DeprecatedWarning: Call to deprecated function __init__(...). API class may be removed in a future release, use falcon.App instead.
  from auth.CAS.REST.service import api
Traceback (most recent call last):
  File "c:\Users\Silph\VS.Code\Python\binance-trading-bot-new-coins-main\main.py", line 1, in <module>
    from trade_client import *
  File "c:\Users\Silph\VS.Code\Python\binance-trading-bot-new-coins-main\trade_client.py", line 1, in <module>
    from auth.binance_auth import *
ModuleNotFoundError: No module named 'auth.binance_auth'

**Comment by ADTC** [comment]
Do: `/usr/local/bin/python3 -m pip install python-binance` or the equivalent for your system.
